.pragma library

var loggingEnabled = true;
var POSITIVE_COLOR = '#00FF00';
var NEGATIVE_COLOR = '#FF0000';

var SQL_TRUE = 1;
var SQL_FALSE = 0;

var CHART_TYPE_UNDEFINED = -1;
var CHART_TYPE_INTRDAY = 0;
var CHART_TYPE_MONTH = 1;
var CHART_TYPE_3_MONTHS = 2;
var CHART_TYPE_YEAR = 3;
var CHART_TYPE_3_YEARS = 4;
var CHART_TYPE_5_YEARS = 5;

var CURRENCY_MAP = [];
CURRENCY_MAP['EUR'] = '\u20AC';
CURRENCY_MAP['USD'] = '$';

var SORTING_ORDER_BY_CHANGE = 0;
var SORTING_ORDER_BY_NAME = 1;

var BACKEND_EUROINVESTOR = 0;
var BACKEND_MOSCOW_EXCHANGE = 1;

// TODO fix typos
var CHART_DATA_DOWNLOAD_STRAGEGY_ALWAYS = 0;
var CHART_DATA_DOWNLOAD_STRAGEGY_ONLY_ON_WIFI = 1;
var CHART_DATA_DOWNLOAD_STRAGEGY_MANUALLY = 2;

var NEWS_DATA_DOWNLOAD_STRATEGY_ALWAYS = 0;
var NEWS_DATA_DOWNLOAD_STRATEGY_ONLY_ON_WIFI = 1;
