name: Watchlist build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2                                 # checkout the repo

      - name: Install qmltestrunner                               # install qmltestrunner packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qtdeclarative5-dev-tools qml-module-qtquick-localstorage
          sudo apt-get install -y qml-module-qtquick-controls qml-module-qttest qt5-qmake

      - name: Run QML / C++ Tests
        run: |
          set -x
          
          cd tests_qml 
          env LC_ALL=de_DE.UTF-8 LC_NUMERIC=de_DE.utf8 qmltestrunner -platform offscreen       
          cd ..                                                   
          cd tests && ./runTests.sh                                

  build:
    name: Build Versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: mkdir output

      - name: Build armv7hl
        id: build_armv7hl
        uses: coderus/github-sfos-build@master
        with:
          release: 4.2.0.21

      - name: Build i486
        id: build_i486
        uses: coderus/github-sfos-build@master
        with:
          release: 4.2.0.21
          arch: i486

      - name: Build aarch64
        id: build_aarch64
        uses: coderus/github-sfos-build@master
        with:
          release: 4.2.0.21
          arch: aarch64

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: rpm-build-result
          path: RPMS

      - name: Create release
        if: contains(github.ref, 'release')
        run: |
          set -x
          assets=()
          for asset in RPMS/*.rpm; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
